### ISSUE TITLE
Discussion: full names for keys and values

### ISSUE THREAD

**Issue by ajturner** [uwdata/vega-lite#436]
In general it would be an improvement for developer experience to use full names when appropriate. for example `"type": "O"` is not clear to someone reading or working on Vega or Vega-Lite documents that this means `Ordinal`. Or `"aggr": "avg"` is `"aggregate": "average"`.

There would be a minimal JSON size growth by using full names but would dramatically improve legibility and editing.

**Comment by kanitw** [comment]
For "O" vs "ordinal", I think this is a reasonable point, we will reconsider when it's closer to 1.0 release. 

For `avg`, I think it's a pretty common function name in other software including SQL, Tableau and Qlikview.
`aggr` is less common but I think it's very easy to guess.  QlikView also use it too.

**Comment by ajturner** [comment]
Thanks for the response.

I generally treat API and specs like this as Developer UX. Avoiding having to guess - or remember shorthand - is preferable.

Similarly the `enc` at the root. Is that 'encoding'?

**Comment by kanitw** [comment]
We actually planned to change `enc` to `encoding`.
Thinking more about your earlier feedback, we will change `aggr` to `aggregate`.

For aggregation function names, we would make it consistent with https://github.com/uwdata/vega.
