### ISSUE TITLE
Binning Bug

### ISSUE THREAD

**Issue by kanitw** [uwdata/vega-lite#454]
Somehow binned scale was now weirdly sorted.
I tried to fix with `sort:true` but that makes vertical bin axes incorrect.
I will probably need to apply `reverse:true`, but I remember that it was broken earlier.

**Comment by kanitw** [comment]
For Vega 1, depends on https://github.com/trifacta/vega/issues/280.

**Comment by domoritz** [comment]
Reproduce with 

```js
{
  "marktype": "bar",
  "encoding": {
    "x": {"bin": {"maxbins": 15},"name": "Horse_Power","type": "Q"},
    "y": {"name": "Miles_per_Gallon","type": "Q","aggregate": "avg"}
  },
  "data": {"url": "data/cars.json"}
}
```

**Comment by domoritz** [comment]
This is extremely bad. How do we go about fixing this?

**Comment by kanitw** [comment]
Have to fix vega -- for vega1?

**Comment by jheer** [comment]
I just fixed the ordinal scale reversal bug filed on Vega 1.5. I had to modify the example spec first (notably, the ordinal scale must have a range definition, e.g., `"range": "height"`).

@arvind We may want to make sure the fix carries over to Vega 2.
