### ISSUE TITLE
Wrong alignment for labels of axis on top. 

### ISSUE THREAD

**Issue by domoritz** [uwdata/vega-lite#481]
```json
{
  "marktype": "point",
  "encoding": {
    "x": {"name": "MPAA_Rating","type": "N"},
    "y": {"name": "Release_Date","type": "N"}
  },
  "config": {"singleHeight": 400,"singleWidth": 400,"largeBandMaxCardinality": 20},
  "data": {"url": "data/movies.json"}
}
```

![screen shot 2015-06-30 at 09 56 25](https://cloud.githubusercontent.com/assets/589034/8436611/5f500816-1f0e-11e5-9e45-25278db31126.png)

**Comment by kanitw** [comment]
I think it's more of wrong rotation for axis on top

**Comment by kanitw** [comment]
<img width="852" alt="vega-lite_editor" src="https://cloud.githubusercontent.com/assets/111269/8767363/05e82dde-2e28-11e5-9c71-64600e0db1fc.png">

Fixed
