### ISSUE TITLE
Remove ALPHA from encoding.

### ISSUE THREAD

**Issue by kanitw** [uwdata/vega-lite#520]
We already hide it from Polestar as it’s a bad practice to encoding something on ALPHA.
So we better just remove it.  

@domoritz  any objection?

**Comment by kanitw** [comment]
If we do so, alpha could become COLOR’s property instead.

**Comment by domoritz** [comment]
Agreed.

**Comment by ajturner** [comment]
Alpha combined with other Paramaters are useful

**Comment by domoritz** [comment]
@ajturner Can you give an example?

**Comment by kanitw** [comment]
@ajturner   

To clarify, we are not removing ALPHA as a feature.  
People can still specify ALPHA.  However, we will not allow mapping variable values to ALPHA as a similar effect can be applied by mapping values to COLOR's saturation but it is harder to perceive if the effect is applied to ALPHA.  

Therefore, in #522 I'm changing ALPHA to become COLOR field's property.
