### ISSUE TITLE
More complex types of visualizations (layers, multiple columns/axes)

### ISSUE THREAD

**Issue by ellisonbg** [uwdata/vega-lite#539]
In some types of plots, you want to put multiple columns of data on a single axes. This shows up often in time series, when there is a single date/time column and multiple columns of time series, but also
in other plots. You could imagine doing a scatterplot (points) on the same axes, with two columns as different colors. From a conceptual perspective, this is similar to faceting, but instead of using a
categorical column, you are using different columns.

Another example is the scatter plot matrix:

http://stanford.edu/~mwaskom/software/seaborn/examples/scatterplot_matrix.html

where the row/col facet fields are not values from a single categorical column, but a set of columns themselves.

I started to discuss this with @jheer @domoritz over email. They mentioned the possibility of introducing new abstractions into the spec to handle these types of things:

* Multiple layers to allow multiple series to be put on a single axes.
* Multiple y axes
* A new composition/layering approach (or "algebra") that would allow multiple vegalite specs to be combined into a single visulization for these types of purposes.

**Comment by kanitw** [comment]
@ellisonbg @domoritz  Thanks for posting this issue. 
Actually I created this issue #24 at the very beginning days of Vega-lite.  

So I'm closing issue to avoid redundancy.

**Comment by ellisonbg** [comment]
ok great!

On Wed, Aug 5, 2015 at 7:16 PM, Kanit Wongsuphasawat <
notifications@github.com> wrote:

> Closed #539 <https://github.com/uwdata/vega-lite/issues/539>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uwdata/vega-lite/issues/539#event-374862127>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
