### ISSUE TITLE
Command line tool

### ISSUE THREAD

**Issue by domoritz** [uwdata/vega-lite#562]
Bundle vega-lite with node in a command line tool that takes a vl spec and outputs a vega spec.

**Comment by domoritz** [comment]
cc/ @jowens

**Comment by jowens** [comment]
Per the Unix philosophy, it would be nice if vl2vg would take the input vega_lite_json_file from stdin as well as from a file. (It's silly for me to write it to a file just so I can read it back in into vl2vg.) One would like to be able to ```cat foo.vl | vl2vg | ...```.

**Comment by domoritz** [comment]
Good point. I mostly copied https://github.com/vega/vega/blob/master/bin/vg2png

I'll add it tonight.

**Comment by jowens** [comment]
Is there an equivalent shorthand->vl command-line (or other) tool as well?

**Comment by domoritz** [comment]
No, but we have the utility functions in vl so it should be easy to copy and paste it together.

**Comment by jowens** [comment]
OK. Perhaps something to document for y'all? You know I'm trying to do this in python, and my flow is pandas outputting JSON data, which I will stick into a VL JSON object, and then run vl2vg, and then use the vega output. I'm not running any vl in that flow at all.

**Comment by domoritz** [comment]
You would have to write a shorthand2vg script that calls https://github.com/uwdata/vega-lite/blob/master/src/compiler/compiler.js#L29

**Comment by jowens** [comment]
Got it. Not a high priority for me, but I'll do that when I need to do that. Thanks!
