### ISSUE TITLE
support "displayName" on encodings

### ISSUE THREAD

**Issue by jowens** [uwdata/vega-lite#571]
All of the gallery visualizations save one use the internal data field name as the axis label. It is likely that users will want to use a different axis label name as the internal data field name (no one really likes underscores in axis labels, do they?). 

In the gallery, the binned plot example has a "size" encoding, which has a "displayName" field, and the displayName is what's displayed atop the legend. However, displayName does not appear to work everywhere (try it on, say, the y axis of a bar plot). It'd be nice if it did.

**Comment by kanitw** [comment]
We actually added   `axis.title` property for this.  

try
```
encoding: {
  x: { ..., axis: {title: "custom title"} }
}
```
(Again, apologies for lack of documentation. We're still in an alpha state but we'll surely have a detailed documentation when we release 1.0)

**Comment by jowens** [comment]
Also I note that axis.title doesn't back-propagate to "shorthand". I like "shorthand"; it'd be nice if axis.title could be part of it.
